
//Separate module that defines the action types to be used. 
export const SEARCH_COURSE = 'SEARCH_COURSE'
export const FETCH_COURSES_BEGIN = 'FETCH_COURSES_BEGIN'
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS'
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE'

export const FETCH_GRADES_BEGIN = 'FETCH_GRADES_BEGIN'
export const FETCH_GRADES_SUCCESS = 'FETCH_GRADES_SUCCESS'
export const FETCH_GRADES_FAILURE = 'FETCH_GRADES_FAILURE'

export const TOGGLE_VALUE = 'TOGGLE_VALUE'
